/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_MUCLoader */

#ifndef _Included_main_MUCLoader
#define _Included_main_MUCLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     main_MUCLoader
 * Method:    doMucLogin
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_main_MUCLoader_doMucLogin
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
